config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :facturas
  resources :product_orders
  resources :razones_comerciales
  resources :razones_sociales
  resources :direcciones_facturas
  resources :direcciones_entregas
  resources :productos
  get 'pedidos/aprobar' => 'pedidos#aprobar'
  get 'pedidos/produccion' => 'pedidos#produccion'
  get 'pedidos/enviado' => 'pedidos#enviado'
  get 'pedidos/entregado' => 'pedidos#entregado'
  resources :pedidos
  get 'productos_especiales/aprobar' => 'productos_especiales#aprobar'
  resources :productos_especiales
  get 'productos_especiales/index'
  root 'home#index'
  get 'home/about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/index'
  get "users/aprobar"
  get "users/empresa"
  get "workers/index"
  get "workers/new"
  post 'workers',  to: 'workers#add_user'
  get 'home/about'
  get 'home/productos'
  get 'home/servicios'
  get 'home/contacto'
  get 'home/reportes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/productos_especiale.rb
class ProductosEspeciale < ApplicationRecord
  belongs_to :user
  validates :image, :presence => true
    has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/controllers/productos_especiales_controller.rb
class ProductosEspecialesController < ApplicationController
  before_action :set_productos_especiale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /productos_especiales
  # GET /productos_especiales.json
  def index
    if current_user.admin
      @newproductos_especiales = ProductosEspeciale.where(aprobado: false)
      @productos_especiales = ProductosEspeciale.where(aprobado: 'Aprobado')
    else
      @productos_especiales = current_user.productos_especiales.where(aprobado: 'Aprobado')
      @newproductos_especiales = current_user.productos_especiales.where(aprobado: false)
    end
    if current_user.empleado?
      @productos_especiales = User.find(current_user.trabajaPara).productos_especiales.where(aprobado: 'Aprobado')
      @newproductos_especiales = User.find(current_user.trabajaPara).productos_especiales.where(aprobado: false)
    
    end
  end

  # GET /productos_especiales/1
  # GET /productos_especiales/1.json
  def show
  end

  # GET /productos_especiales/new
  def new
    @productos_especiale = current_user.productos_especiales.build
  end

  # GET /productos_especiales/1/edit
  def edit
    if current_user.admin
      @productos_especiales = ProductosEspeciale.all
    else
      @productos_especiales = current_user.productos_especiales
    end
  end

  # POST /productos_especiales
  # POST /productos_especiales.json
  def create
   
    @productos_especiale = current_user.productos_especiales.build(productos_especiale_params)

    respond_to do |format|
      if @productos_especiale.save
        format.html { redirect_to @productos_especiale, notice: 'Productos especiale was successfully created.' }
        format.json { render :show, status: :created, location: @productos_especiale }
      else
        format.html { render :new }
        format.json { render json: @productos_especiale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos_especiales/1
  # PATCH/PUT /productos_especiales/1.json
  def update
    respond_to do |format|
      if @productos_especiale.update(productos_especiale_params)
        format.html { redirect_to @productos_especiale, notice: 'Productos especiale was successfully updated.' }
        format.json { render :show, status: :ok, location: @productos_especiale }
      else
        format.html { render :edit }
        format.json { render json: @productos_especiale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos_especiales/1
  # DELETE /productos_especiales/1.json
  def destroy
    @productos_especiale.destroy
    respond_to do |format|
      format.html { redirect_to productos_especiales_url, notice: 'Productos especiale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def aprobar
    ProductosEspeciale.where(id: params[:productos_especiale_id]).update_all(aprobado: 'Aprobado')
    redirect_to :controller => 'productos_especiales', :action => 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productos_especiale
      @productos_especiale = ProductosEspeciale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def productos_especiale_params
      params.require(:productos_especiale).permit(:nombre, :acabado, :aprobado, :user_id, :image)
    end
end

app/helpers/productos_especiales_helper.rb
module ProductosEspecialesHelper
end

app/views/productos_especiales/_form.html.erb
<%= form_for(productos_especiale, html: {multipart: true}) do |f| %>
  <% if productos_especiale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(productos_especiale.errors.count, "error") %> prohibited this productos_especiale from being saved:</h2>

      <ul>
      <% productos_especiale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :acabado %>
    <%= f.text_field :acabado %>
  </div>

  <div class="form-group">
    <%= f.label :image, 'Imagen' %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <%=f.hidden_field :aprobado, :value => "false"%> 

  <div class="actions">
    <%= f.submit :value => 'Continuar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/productos_especiales/aprobar.html.erb
<h1>Aprobado</h1>

app/views/productos_especiales/edit.html.erb
<div class="divide80"></div>

<div class="login-form">
	<h4>Editar Producto</h4>
	<%= render 'form', productos_especiale: @productos_especiale %>
</div>


<%= link_to 'Ver', @productos_especiale, :class => 'btn btn-primary' %> |
<%= link_to 'Volver', productos_especiales_path, :class => 'btn btn-primary' %>

app/views/productos_especiales/index.html.erb
<p id="notice"><%= notice %></p>
<div class="divide80"></div>

<div class="container">
  <div class="row">  
        <div class="col-md-12">
            <div>
                <h3>Productos especiales</h3>
                <div role="tabpanel" class="login-regiter-tabs">

                  <!-- Nav tabs -->
                  <ul class="nav nav-tabs text-center" role="tablist">
                      <li role="presentation" class="active"><a href="#aprobados" aria-controls="login" role="tab" data-toggle="tab">Aprobados</a></li>
                      <li role="presentation"><a href="#noaprobados" aria-controls="profile" role="tab" data-toggle="tab">No aprobados</a></li>
                  </ul>

                  <!-- Tab panes -->
                  <div class="tab-content">
                      <div role="tabpanel" class="tab-pane active" id="aprobados">
                        <h4 class="margin30 text-center">Productos aprobados</h4>
                          <div class="row">
                            <% @productos_especiales.each do |producto| %>
                              <div class="col-md-3">
                                <div class="item_holder">
                                    <a href="#"><%= image_tag producto.image.url, :class => "thumb-image" %></a>
                                    <div class="title">
                                        <h5><%= producto.nombre %><br><%= producto.acabado %></h5>
                                    </div>
                                    <%= link_to 'Ver', producto %>
                                    <% if current_user.admin? %>
                                      <%= link_to 'Editar', edit_producto_path(producto) %>
                                    <%= link_to 'Borrar', producto, method: :delete, data: { confirm: 'Are you sure?' } %>
                                    <% end %>
                                </div><!--item holder-->
                              </div><!--col end-->
                            <% end %>
                          </div>
                      </div><!--login tab end-->
                      <div role="tabpanel" class="tab-pane" id="noaprobados">
                          <h4 class="margin30 text-center">Productos no aprobados</h4>
                          <div class="row">
                            <% @newproductos_especiales.each do |producto| %>
                              <div class="col-md-3">
                                <div class="item_holder">
                                    <a href="#"><%= image_tag producto.image.url, :class => "thumb-image" %></a>
                                    <div class="title">
                                        <h5><%= producto.nombre %><br><%= producto.acabado %></h5>
                                    </div>
                                    <% if !producto.aprobado && current_user.admin? %>
                                            <%= button_to "Aprobar", { :controller => "productos_especiales", :action => "aprobar" }, :method => :get, params: { productos_especiale_id: producto.id } %>
                                    <% end %>
                                    <%= link_to 'Ver', producto %>
                                    <% if current_user.admin? %>
                                      <%= link_to 'Editar', edit_producto_path(producto) %>
                                    <%= link_to 'Borrar', producto, method: :delete, data: { confirm: 'Are you sure?' } %>
                                    <% end %>
                                </div><!--item holder-->
                              </div><!--col end-->
                            <% end %>
                          </div>
                      </div><!--register tab end-->
                  </div>
                </div>
            </div>
        </div>
    </div>
    <% if !current_user.admin? && !current_user.empleado? %>
      <%= link_to 'Nuevo producto especial', new_productos_especiale_path, class: 'btn btn-primary' %>
    <% end %>
    <div class="divide80"></div>


</div>

app/views/productos_especiales/new.html.erb
<div class="divide80"></div>

<div class="login-form">
	<h4>Nuevo producto especial</h4>
	<%= render 'form', productos_especiale: @productos_especiale %>
</div>

<div class="divide40"></div>
<%= link_to 'Back', productos_especiales_path, class: 'btn btn-primary' %>

<div class="divide40"></div>

app/views/productos_especiales/show.html.erb
<p id="notice"><%= notice %></p>

<div class="divide80"></div>
<p>
  <strong>Nombre:</strong>
  <%= @productos_especiale.nombre %>
</p>

<p>
  <strong>Acabado:</strong>
  <%= @productos_especiale.acabado %>
</p>

<p>
  <strong>Aprobado:</strong>
  <%= @productos_especiale.aprobado %>
</p>

<p>
    <strong>Producto:</strong> 
    <br>
    <div class="row">
      <div class="col-md-3">
        <%= image_tag @productos_especiale.image.url %>
      </div>
    </div>
    
  </p>

<% if current_user.admin? %>
	<p>
	  <strong>User:</strong>
	  <%= @productos_especiale.user.id %>
	</p>
<% end %>

<%= link_to 'Edit', edit_productos_especiale_path(@productos_especiale), :class => 'btn btn-primary' %> |
<%= link_to 'Back', productos_especiales_path, :class => 'btn btn-primary' %>
<div class="divide40"></div>