config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :facturas
  resources :product_orders
  resources :razones_comerciales
  resources :razones_sociales
  resources :direcciones_facturas
  resources :direcciones_entregas
  resources :productos
  get 'pedidos/aprobar' => 'pedidos#aprobar'
  get 'pedidos/produccion' => 'pedidos#produccion'
  get 'pedidos/enviado' => 'pedidos#enviado'
  get 'pedidos/entregado' => 'pedidos#entregado'
  resources :pedidos
  get 'productos_especiales/aprobar' => 'productos_especiales#aprobar'
  resources :productos_especiales
  get 'productos_especiales/index'
  root 'home#index'
  get 'home/about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/index'
  get "users/aprobar"
  get "users/empresa"
  get "workers/index"
  get "workers/new"
  post 'workers',  to: 'workers#add_user'
  get 'home/about'
  get 'home/productos'
  get 'home/servicios'
  get 'home/contacto'
  get 'home/reportes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	validates :title, :presence => true
	validates :body, :presence => true
	has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/direcciones_entrega.rb
class DireccionesEntrega < ApplicationRecord
  belongs_to :user
end

app/models/direcciones_factura.rb
class DireccionesFactura < ApplicationRecord
  belongs_to :user
end

app/models/factura.rb
class Factura < ApplicationRecord
	belongs_to :pedido
	validates :image, :presence => true
    has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/pedido.rb
class Pedido < ApplicationRecord
	belongs_to :user
	has_many :product_orders
	has_one :factura
	has_one :razones_comerciale
	
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
	belongs_to :pedido
	has_one :producto
end

app/models/producto.rb
class Producto < ApplicationRecord
	validates :image, :presence => true
	has_attached_file :image
    # has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>"}
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/productos_especiale.rb
class ProductosEspeciale < ApplicationRecord
  belongs_to :user
  validates :image, :presence => true
    has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/razones_comerciale.rb
class RazonesComerciale < ApplicationRecord
  belongs_to :razones_sociale
end

app/models/razones_sociale.rb
class RazonesSociale < ApplicationRecord
  belongs_to :user
  has_many :razones_comerciales
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pedidos
  has_many :direcciones_entregas
  has_many :direcciones_facturas
  has_many :razones_sociales
  has_many :productos_especiales
  def active_for_authentication? 
    super && aprobado? 
  end 

  def inactive_message 
    if !aprobado? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @content1 = Content.find(1)
    @content2 = Content.find(2)
    @content3 = Content.find(3)
    @content4 = Content.find(4)
    @content5 = Content.find(5)
    @content6 = Content.find(6)
  end

  def about
    @content1 = Content.find(8)
  end

  def productos
  end

  def servicios
  end

  def contacto
  end

  def reportes
    @productos = ProductOrder.where(:pedido_id => Pedido.where.not(:tipo => 'Especial' ))
    @reporte = @productos.group("producto_id").sum(:cantidad)
    @cantPedidos = Pedido.count()
    @individuos = User.where(:individuo => true).count
    @empresas = User.where(:empresa => true).count
  end 
end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  before_action :set_product_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /product_orders
  # GET /product_orders.json
  def index
    @pedido = Pedido.find(params[:pedido])
    @product_orders = @pedido.product_orders
  end

  # GET /product_orders/1
  # GET /product_orders/1.json
  def show
    @pedido = Pedido.find(@product_order.pedido_id)
  end

  # GET /product_orders/new
  def new
    @pedido = Pedido.find(params[:pedido])
    @product_order = @pedido.product_orders.build
    if (@pedido.tipo == "Especial")
      if User.find(@pedido.user_id).empleado
        @productos = User.find(User.find(@pedido.user_id).trabajaPara).productos_especiales
      else
        @productos = User.find(@pedido.user_id).productos_especiales
      end
    else
      @productos = Producto.all
    end
  end

  # GET /product_orders/1/edit
  def edit
    @pedido = Pedido.find(@product_order.pedido_id)
    @productos = Producto.all
  end

  # POST /product_orders
  # POST /product_orders.json
  def create
    @pedido = Pedido.find(params[:product_order][:pedido_id])
    @product_order = @pedido.product_orders.build(product_order_params)
    respond_to do |format|
      if @product_order.save
        format.html { redirect_to product_orders_path(pedido: @pedido.id), notice: 'Product order was successfully created.' }
        format.json { render :show, status: :created, location: @product_order }
      else
        format.html { render :new }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_orders/1
  # PATCH/PUT /product_orders/1.json
  def update
    respond_to do |format|
      if @product_order.update(product_order_params)
        format.html { redirect_to @product_order, notice: 'Product order was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_order }
      else
        format.html { render :edit }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_orders/1
  # DELETE /product_orders/1.json
  def destroy
    @pedido = Pedido.find(@product_order.pedido_id)
    @product_order.destroy
    respond_to do |format|
      format.html { redirect_to product_orders_url(:pedido => @pedido), notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_order
      @product_order = ProductOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_order_params
      params.require(:product_order).permit(:cantidad, :producto_id, :pedido_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :correct_user

	def index
	    @newUsersIndividuo = User.where(aprobado: false, individuo: true)
	    @usersIndividuo = User.where(aprobado: true, individuo: true)
	    @newUsersEmpresa = User.where(aprobado: false, empresa: true)
	    @usersEmpresa = User.where(aprobado: true, empresa: true)
	    @empleados = User.where(empleado: true)
	end

	def aprobar
		@aprobarUsuario = User.where(id: params[:user_id]).update_all(aprobado: true)
		redirect_to :controller => 'users', :action => 'index'
	end

	def empresa
		User.where(id: params[:user_id]).update_all(empresa: true, individuo: false)
		redirect_to :controller => 'users', :action => 'index'
	end
	
	private
    def correct_user
      if !current_user.admin?
        redirect_to :controller => 'home', :action => 'index'
      end    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/product_orders_helper.rb
module ProductOrdersHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/product_orders/_form.html.erb
<%= form_for(product_order) do |f| %>
  <% if product_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_order.errors.count, "error") %> prohibited this product_order from being saved:</h2>

      <ul>
      <% product_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <% @productos.each do |producto| %>
      <div class="col-md-2 text-center">
        <%= image_tag producto.image.url, :class => "thumb-image" %>
        <%= f.radio_button :producto_id, producto.id, :required => true %>
        <%= f.label :producto_id, producto.nombre %>
      </div>
    <% end %>


  </div>
  
  <div class="field">
    <%= f.label :cantidad %>
    <%= f.number_field :cantidad, :required => true, :min => 1%>
  </div>
  
  <div class="divide40"></div>
  <div class="actions">
    <%= f.hidden_field :pedido_id, value: @pedido.id %>
    <%= f.submit :value => 'Añadir producto', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/product_orders/edit.html.erb
<div class="divide80"></div>

<h1>Editar producto</h1>

<%= render 'form', product_order: @product_order %>

<%= link_to 'Ver', @product_order, class:'btn btn-primary'  %> |
<%= link_to 'Regresar', product_orders_path(:pedido => @pedido), class:'btn btn-primary'  %>
<div class="divide40"></div>

app/views/product_orders/index.html.erb
<div class="divide80"></div>
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Producto</th>
      <th>Acabado</th>
      <th>Imagen</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_orders.each do |product_order| %>
      <tr>
        <td><%= product_order.cantidad %></td>
        <% if Pedido.find(product_order.pedido_id).tipo == 'Especial' %>
          <td><%= ProductosEspeciale.find(product_order.producto_id).nombre %></td>
          <td><%= ProductosEspeciale.find(product_order.producto_id).acabado %></td>
          <td><%= image_tag ProductosEspeciale.find(product_order.producto_id).image.url, :class => "small-img" %></td>
        <% else %>
          <td><%= Producto.find(product_order.producto_id).nombre %></td>
          <td><%= Producto.find(product_order.producto_id).acabado %></td>
          <td><%= image_tag Producto.find(product_order.producto_id).image.url, :class => "small-img" %></td>
        <% end %>
        <td><%= link_to 'Editar', edit_product_order_path(product_order) %></td>
        <td><%= link_to 'Eliminar', product_order, method: :delete, data: { confirm: '¿Desea eliminar el producto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo producto', new_product_order_path(:pedido => @pedido), :class => 'btn btn-primary' %>
<% if current_user.admin? %>
  <%= link_to 'Continuar', edit_pedido_path(@pedido, :nuevo => 'true'), :class => 'btn btn-primary' %>
<% else %>
  <%= link_to 'Continuar', pedidos_path, :class => 'btn btn-primary' %>
<% end %>
<div class="divide40"></div>

app/views/product_orders/new.html.erb
<div class="divide80"></div>

<h1>Añadir producto</h1>

<div class="login-form">
	<%= render 'form', product_order: @product_order %>
</div>

<div class="divide40"></div>
<%= link_to 'Regresar', product_orders_path(:pedido => @pedido), :class => 'btn btn-primary' %>
<div class="divide40"></div>

app/views/product_orders/show.html.erb
<div class="divide80"></div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @product_order.cantidad %>
</p>

<p>
  <strong>Producto:</strong>
  <%= Producto.find(@product_order.producto_id).nombre + ' ' + Producto.find(@product_order.producto_id).acabado %>
</p>

<p>
  <strong>Pedido:</strong>
  <%= @product_order.pedido_id %>
</p>

<%= link_to 'Editar', edit_product_order_path(@product_order), class:'btn btn-primary'  %> |
<%= link_to 'Regresar', product_orders_path(:pedido => @pedido), class:'btn btn-primary'  %>

<div class="divide40"></div>