config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :facturas
  resources :product_orders
  resources :razones_comerciales
  resources :razones_sociales
  resources :direcciones_facturas
  resources :direcciones_entregas
  resources :productos
  get 'pedidos/aprobar' => 'pedidos#aprobar'
  get 'pedidos/produccion' => 'pedidos#produccion'
  get 'pedidos/enviado' => 'pedidos#enviado'
  get 'pedidos/entregado' => 'pedidos#entregado'
  resources :pedidos
  get 'productos_especiales/aprobar' => 'productos_especiales#aprobar'
  resources :productos_especiales
  get 'productos_especiales/index'
  root 'home#index'
  get 'home/about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/index'
  get "users/aprobar"
  get "users/empresa"
  get "workers/index"
  get "workers/new"
  post 'workers',  to: 'workers#add_user'
  get 'home/about'
  get 'home/productos'
  get 'home/servicios'
  get 'home/contacto'
  get 'home/reportes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	validates :title, :presence => true
	validates :body, :presence => true
	has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/direcciones_entrega.rb
class DireccionesEntrega < ApplicationRecord
  belongs_to :user
end

app/models/direcciones_factura.rb
class DireccionesFactura < ApplicationRecord
  belongs_to :user
end

app/models/factura.rb
class Factura < ApplicationRecord
	belongs_to :pedido
	validates :image, :presence => true
    has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/pedido.rb
class Pedido < ApplicationRecord
	belongs_to :user
	has_many :product_orders
	has_one :factura
	has_one :razones_comerciale
	
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
	belongs_to :pedido
	has_one :producto
end

app/models/producto.rb
class Producto < ApplicationRecord
	validates :image, :presence => true
	has_attached_file :image
    # has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>"}
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/productos_especiale.rb
class ProductosEspeciale < ApplicationRecord
  belongs_to :user
  validates :image, :presence => true
    has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/razones_comerciale.rb
class RazonesComerciale < ApplicationRecord
  belongs_to :razones_sociale
end

app/models/razones_sociale.rb
class RazonesSociale < ApplicationRecord
  belongs_to :user
  has_many :razones_comerciales
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pedidos
  has_many :direcciones_entregas
  has_many :direcciones_facturas
  has_many :razones_sociales
  has_many :productos_especiales
  def active_for_authentication? 
    super && aprobado? 
  end 

  def inactive_message 
    if !aprobado? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @content1 = Content.find(1)
    @content2 = Content.find(2)
    @content3 = Content.find(3)
    @content4 = Content.find(4)
    @content5 = Content.find(5)
    @content6 = Content.find(6)
  end

  def about
    @content1 = Content.find(8)
  end

  def productos
  end

  def servicios
  end

  def contacto
  end

  def reportes
    @productos = ProductOrder.where(:pedido_id => Pedido.where.not(:tipo => 'Especial' ))
    @reporte = @productos.group("producto_id").sum(:cantidad)
    @cantPedidos = Pedido.count()
    @individuos = User.where(:individuo => true).count
    @empresas = User.where(:empresa => true).count
  end 
end

app/controllers/razones_sociales_controller.rb
class RazonesSocialesController < ApplicationController
  before_action :set_razones_sociale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :correct_user
  # GET /razones_sociales
  # GET /razones_sociales.json
  def index
    @razones_sociales = current_user.razones_sociales
  end

  # GET /razones_sociales/1
  # GET /razones_sociales/1.json
  def show
  end

  # GET /razones_sociales/new
  def new
    @razones_sociale = current_user.razones_sociales.build
  end

  # GET /razones_sociales/1/edit
  def edit
  end

  # POST /razones_sociales
  # POST /razones_sociales.json
  def create
    @razones_sociale = current_user.razones_sociales.build(razones_sociale_params)

    respond_to do |format|
      if @razones_sociale.save
        format.html { redirect_to @razones_sociale, notice: 'Razones sociale was successfully created.' }
        format.json { render :show, status: :created, location: @razones_sociale }
      else
        format.html { render :new }
        format.json { render json: @razones_sociale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /razones_sociales/1
  # PATCH/PUT /razones_sociales/1.json
  def update
    respond_to do |format|
      if @razones_sociale.update(razones_sociale_params)
        format.html { redirect_to @razones_sociale, notice: 'Razones sociale was successfully updated.' }
        format.json { render :show, status: :ok, location: @razones_sociale }
      else
        format.html { render :edit }
        format.json { render json: @razones_sociale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /razones_sociales/1
  # DELETE /razones_sociales/1.json
  def destroy
    @razones_sociale.destroy
    respond_to do |format|
      format.html { redirect_to razones_sociales_url, notice: 'Razones sociale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_razones_sociale
      @razones_sociale = RazonesSociale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def razones_sociale_params
      params.require(:razones_sociale).permit(:nombre, :rfc, :email, :direccion, :telefono, :notas, :user_id)
    end

    def correct_user
      if !current_user.empresa?
        redirect_to :controller => 'home', :action => 'index'
      end    
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :correct_user

	def index
	    @newUsersIndividuo = User.where(aprobado: false, individuo: true)
	    @usersIndividuo = User.where(aprobado: true, individuo: true)
	    @newUsersEmpresa = User.where(aprobado: false, empresa: true)
	    @usersEmpresa = User.where(aprobado: true, empresa: true)
	    @empleados = User.where(empleado: true)
	end

	def aprobar
		@aprobarUsuario = User.where(id: params[:user_id]).update_all(aprobado: true)
		redirect_to :controller => 'users', :action => 'index'
	end

	def empresa
		User.where(id: params[:user_id]).update_all(empresa: true, individuo: false)
		redirect_to :controller => 'users', :action => 'index'
	end
	
	private
    def correct_user
      if !current_user.admin?
        redirect_to :controller => 'home', :action => 'index'
      end    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/razones_sociales_helper.rb
module RazonesSocialesHelper
end

app/views/razones_sociales/_form.html.erb
<%= form_for(razones_sociale) do |f| %>
  <% if razones_sociale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(razones_sociale.errors.count, "error") %> prohibited this razones_sociale from being saved:</h2>

      <ul>
      <% razones_sociale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre, '*Nombre' %>
    <%= f.text_field :nombre,:required => true  %>
  </div>

  <div class="field">
    <%= f.label :rfc, '*RFC' %>
    <%= f.text_field :rfc,:required => true  %>
  </div>

  <div class="field">
    <%= f.label :email, '*Email' %>
    <%= f.text_field :email,:required => true  %>
  </div>

  <div class="field">
    <%= f.label :direccion, '*Dirección' %>
    <%= f.text_field :direccion,:required => true  %>
  </div>

  <div class="field">
    <%= f.label :telefono, '*Teléfono' %>
    <%= f.text_field :telefono,:required => true  %>
  </div>

  <div class="field">
    <%= f.label :notas %>
    <%= f.text_area :notas %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>


  <div class="actions">
    <%= f.submit :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/razones_sociales/edit.html.erb
<div class="divide80"></div>

<div class="login-form">
	<h4>Editar Razón Social</h4>
	<%= render 'form', razones_sociale: @razones_sociale %>
</div>


<%= link_to 'Ver', @razones_sociale, class:'btn btn-primary' %> |
<%= link_to 'Regresar', razones_sociales_path, class:'btn btn-primary' %>

<div class="divide40"></div>

app/views/razones_sociales/index.html.erb
<div class="divide80"></div>

<p id="notice"><%= notice %></p>

<h1>Razones Sociales</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>RFC</th>
      <th>Email</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Notas</th>
      <th>Razones comerciales</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @razones_sociales.each do |razones_sociale| %>
      <tr>
        <td><%= razones_sociale.nombre %></td>
        <td><%= razones_sociale.rfc %></td>
        <td><%= razones_sociale.email %></td>
        <td><%= razones_sociale.direccion %></td>
        <td><%= razones_sociale.telefono %></td>
        <td><%= razones_sociale.notas %></td>
        <td><%= link_to 'Ver Razones Comerciales', razones_comerciales_path(:razon => razones_sociale) %></td>
        <td><%= link_to 'Ver', razones_sociale %></td>
        <td><%= link_to 'Editar', edit_razones_sociale_path(razones_sociale) %></td>
        <td><%= link_to 'Eliminar', razones_sociale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Razón Social', new_razones_sociale_path, class:'btn btn-primary' %>

<div class="divide40"></div>

app/views/razones_sociales/new.html.erb
<div class="divide80"></div>

<div class="login-form">
	<h4>Nueva Razón Social</h4>
	<%= render 'form', razones_sociale: @razones_sociale %>
</div>


<%= link_to 'Regresar', razones_sociales_path, class:'btn btn-primary' %>

<div class="divide40"></div>

app/views/razones_sociales/show.html.erb
<div class="divide80"></div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @razones_sociale.nombre %>
</p>

<p>
  <strong>RFC:</strong>
  <%= @razones_sociale.rfc %>
</p>

<p>
  <strong>Email:</strong>
  <%= @razones_sociale.email %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @razones_sociale.direccion %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @razones_sociale.telefono %>
</p>

<p>
  <strong>Notas:</strong>
  <%= @razones_sociale.notas %>
</p>



<%= link_to 'Editar', edit_razones_sociale_path(@razones_sociale), class:'btn btn-primary' %> |
<%= link_to 'Regresar', razones_sociales_path, class:'btn btn-primary' %>

<div class="divide40"></div>