config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :facturas
  resources :product_orders
  resources :razones_comerciales
  resources :razones_sociales
  resources :direcciones_facturas
  resources :direcciones_entregas
  resources :productos
  get 'pedidos/aprobar' => 'pedidos#aprobar'
  get 'pedidos/produccion' => 'pedidos#produccion'
  get 'pedidos/enviado' => 'pedidos#enviado'
  get 'pedidos/entregado' => 'pedidos#entregado'
  resources :pedidos
  get 'productos_especiales/aprobar' => 'productos_especiales#aprobar'
  resources :productos_especiales
  get 'productos_especiales/index'
  root 'home#index'
  get 'home/about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/index'
  get "users/aprobar"
  get "users/empresa"
  get "workers/index"
  get "workers/new"
  post 'workers',  to: 'workers#add_user'
  get 'home/about'
  get 'home/productos'
  get 'home/servicios'
  get 'home/contacto'
  get 'home/reportes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	validates :title, :presence => true
	validates :body, :presence => true
	has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/direcciones_entrega.rb
class DireccionesEntrega < ApplicationRecord
  belongs_to :user
end

app/models/direcciones_factura.rb
class DireccionesFactura < ApplicationRecord
  belongs_to :user
end

app/models/factura.rb
class Factura < ApplicationRecord
	belongs_to :pedido
	validates :image, :presence => true
    has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/pedido.rb
class Pedido < ApplicationRecord
	belongs_to :user
	has_many :product_orders
	has_one :factura
	has_one :razones_comerciale
	
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
	belongs_to :pedido
	has_one :producto
end

app/models/producto.rb
class Producto < ApplicationRecord
	validates :image, :presence => true
	has_attached_file :image
    # has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>"}
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/productos_especiale.rb
class ProductosEspeciale < ApplicationRecord
  belongs_to :user
  validates :image, :presence => true
    has_attached_file :image
    validates_attachment_content_type :image,
        :content_type => /\Aimage\/.*\Z/
    validates_attachment :image, size: { in: 0..5.megabytes }
end

app/models/razones_comerciale.rb
class RazonesComerciale < ApplicationRecord
  belongs_to :razones_sociale
end

app/models/razones_sociale.rb
class RazonesSociale < ApplicationRecord
  belongs_to :user
  has_many :razones_comerciales
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pedidos
  has_many :direcciones_entregas
  has_many :direcciones_facturas
  has_many :razones_sociales
  has_many :productos_especiales
  def active_for_authentication? 
    super && aprobado? 
  end 

  def inactive_message 
    if !aprobado? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @content1 = Content.find(1)
    @content2 = Content.find(2)
    @content3 = Content.find(3)
    @content4 = Content.find(4)
    @content5 = Content.find(5)
    @content6 = Content.find(6)
  end

  def about
    @content1 = Content.find(8)
  end

  def productos
  end

  def servicios
  end

  def contacto
  end

  def reportes
    @productos = ProductOrder.where(:pedido_id => Pedido.where.not(:tipo => 'Especial' ))
    @reporte = @productos.group("producto_id").sum(:cantidad)
    @cantPedidos = Pedido.count()
    @individuos = User.where(:individuo => true).count
    @empresas = User.where(:empresa => true).count
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :correct_user

	def index
	    @newUsersIndividuo = User.where(aprobado: false, individuo: true)
	    @usersIndividuo = User.where(aprobado: true, individuo: true)
	    @newUsersEmpresa = User.where(aprobado: false, empresa: true)
	    @usersEmpresa = User.where(aprobado: true, empresa: true)
	    @empleados = User.where(empleado: true)
	end

	def aprobar
		@aprobarUsuario = User.where(id: params[:user_id]).update_all(aprobado: true)
		redirect_to :controller => 'users', :action => 'index'
	end

	def empresa
		User.where(id: params[:user_id]).update_all(empresa: true, individuo: false)
		redirect_to :controller => 'users', :action => 'index'
	end
	
	private
    def correct_user
      if !current_user.admin?
        redirect_to :controller => 'home', :action => 'index'
      end    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/product_orders_helper.rb
module ProductOrdersHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/home/_footer.html.erb
<footer id="footer">
            <div class="container">

                <div class="row">
                    <div class="col-md-3 col-sm-6 margin30">
                        <div class="footer-col">
                            <h3><%= Content.find(7).title %></h3>
                            <p>
                                <%= Content.find(7).body %>
                            </p>
                            <% if user_signed_in? %>
                                <% if current_user.admin? %>
                                    <%= link_to 'Edit', edit_content_path(Content.find(7)) %>
                                <% end %>
                            <% end %>
                        </div>                        
                    </div><!--footer col-->
                    <div class="col-md-3 col-sm-6 margin30">
                        <div class="footer-col">
                            <h3>Contacto</h3>

                            <ul class="list-unstyled contact">
                                <li><p><strong>Dirección:</strong> Cancún</p></li> 
                                <li><p><strong>E-mail:</strong> <a href="#">decovi@decovi.com</a></p></li>
                                <li> <p><strong>Teléfono:</strong> 8123456789</p></li>
                              

                            </ul>
                        </div>                        
                    </div><!--footer col-->
                </div>
            </div>
        </footer><!--default footer end here-->

app/views/home/_header.html.erb
<div class="top-bar-dark">            
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-right">
                <ul class="list-inline top-dark-right">
                <% if user_signed_in? %>
                  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'Log In', new_user_session_path %></li>
                  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Static navbar -->
<div class="navbar navbar-default navbar-static-top yamm sticky" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'DECOVI', root_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <%= link_to 'Home', root_path%>
                </li>
                <li class="dropdown ">
                    <%= link_to 'Información', home_about_path %>
                </li>
                <li class="dropdown ">
                    <%= link_to 'Productos', productos_path%>
                </li>
                <li class="dropdown ">
                    <%= link_to 'Servicios', home_servicios_path%>
                </li>
                <li class="dropdown ">
                    <%= link_to 'Contacto', home_contacto_path%>
                </li>
                <% if user_signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pedidos</a>
                        <ul class="dropdown-menu" role="menu">
                            <li><%= link_to 'Nuevo Pedido', new_pedido_path %></li>
                            <li><%= link_to 'Listar Pedidos', pedidos_path %></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administrar</a>
                        <ul class="dropdown-menu" role="menu">
                            <li><%= link_to 'Edit', edit_user_registration_path %></li>
                            <li><%= link_to 'Productos especiales', productos_especiales_path %></li>
                            <% if current_user.admin? %>
                                <li><%= link_to 'Users', users_index_path %></li>
                                <li><%= link_to 'Reportes', home_reportes_path %></li>
                            <% end %>
                            <% if current_user.empresa? %>
                                <li><%= link_to 'Workers', workers_index_path %></li>
                                <li><%= link_to 'Razones sociales', razones_sociales_path %></li>
                            <% end %>
                            <% if current_user.individuo? %>
                                <li><%= link_to 'Direcciones de Entrega', direcciones_entregas_path %></li>
                                <li><%= link_to 'Direcciones de Facturación', direcciones_facturas_path %></li>
                            <% end %>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/home/about.html.erb
<div class="divide80"></div>
<div class="container">
    <div class="row">
        <div class="col-md-6 margin20">
            <h2 class="heading"><%= @content1.title %></h2>
            <p>
                <%= @content1.body %>
            </p>
            <% if user_signed_in? %>
                <% if current_user.admin? %>
                    <%= link_to 'Edit', edit_content_path(@content1) %>
                <% end %>
            <% end %>
        </div>
        <div class="col-md-6">
            <% if @content1.image.exists? %>
                <%= image_tag @content1.image.url, :class => 'thumb-image' %>
            <% else %>
                <%= image_tag("imgDecovi.png", class:'img-responsive') %>
            <% end %>
        </div>
    </div>
</div>
<div class="divide40"></div>

app/views/home/contacto.html.erb
<div class="divide60"></div>
<div class="container">
    <div class="row">
        <div class="col-md-8 margin30">
            <h3 class="heading">Contáctanos</h3>
            <div class="form-contact">
                <div class="required">
                    <p>( <span>*</span> requerido )</p>
                </div>

               <form name="sentMessage" id="contactForm" method="post" novalidate>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="row control-group">
                                <div class="form-group col-xs-12 controls">
                                    <label>Nombre<span>*</span></label>
                                    <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                                    <p class="help-block"></p>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-6">
                            <div class="row control-group">
                                <div class="form-group col-xs-12 controls">
                                    <label>Email<span>*</span></label>
                                    <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                                    <p class="help-block"></p>
                                </div>
                            </div> 
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12  controls">
                            <label>Teléfono<span>*</span></label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 controls">
                            <label>Mensaje<span>*</span></label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-theme-bg btn-lg">Enviar</button>
                        </div>
                    </div>
                </form>

            </div><!--contact form-->
        </div>
        <div class="col-md-4">
            <h3 class="heading">Información</h3>
            <ul class="list-unstyled contact contact-info">
                <li><p><strong>Dirección:</strong> Cancún, México</p></li> 
                <li><p><strong>Email:</strong> <a href="#">decovi@decovi.com</a></p></li>
                <li> <p><strong>Teléfono:</strong> +91 1800 2345 2132</p></li>
            </ul>
  
        </div>
    </div>
</div>

app/views/home/index.html.erb
<section id="home-parallax" class="parallax" data-stellar-background-ratio="0.5">
    <div class="container text-center">
        <h1 class="white"><%= @content1.title %></h1>
        <p class="lead"><%= @content1.body %></p>
        <% if user_signed_in? %>
            <% if current_user.admin? %>
                <%= link_to 'Edit', edit_content_path(@content1) %>
            <% end %>
        <% end %>
        <span class="parallax-buttons">
            <%= link_to 'Ver productos', productos_path, class: "btn border-white btn-lg"%>
        </span>
    </div>
</section><!--parallax-background-->

<div class="divide60"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="center-heading">
                <h2><%= @content2.title %></h2>
                <span class="center-line"></span>
                <p class="sub-text margin40">
                    <%= @content2.body %></p>
                <% if user_signed_in? %>
                    <% if current_user.admin? %>
                        <%= link_to 'Edit', edit_content_path(@content2) %>
                    <% end %>
                <% end %>
            </div>
        </div>

    </div><!--center heading end-->
    <div class="divide50"></div>
    <div class="row">
        <div class="col-md-3 col-sm-6 margin30">
            <div class="colored-boxed green">
                <h3><%= @content3.title %></h3>
                <span class="center-line"></span>
                <p>
                    <%= @content3.body %>
                </p>
                <% if user_signed_in? %>
                    <% if current_user.admin? %>
                        <%= link_to 'Edit', edit_content_path(@content3) %>
                    <% end %>
                <% end %>
            </div>
        </div><!--colored boxed col end-->
        <div class="col-md-3 col-sm-6 margin30">
            <div class="colored-boxed dark">
                <h3><%= @content4.title %></h3>
                <span class="center-line"></span>
                <p>
                    <%= @content4.body %> 
                </p>
                <% if user_signed_in? %>
                    <% if current_user.admin? %>
                        <%= link_to 'Edit', edit_content_path(@content4) %>
                    <% end %>
                <% end %>
            </div>
        </div><!--colored boxed col end-->
        <div class="col-md-3 col-sm-6 margin30">
            <div class="colored-boxed blue">
                <h3><%= @content5.title %></h3>
                <span class="center-line"></span>
                <p>
                    <%= @content5.body %> 
                </p>
                <% if user_signed_in? %>
                    <% if current_user.admin? %>
                        <%= link_to 'Edit', edit_content_path(@content5) %>
                    <% end %>
                <% end %>
            </div>
        </div><!--colored boxed col end-->
        <div class="col-md-3 col-sm-6 margin30">
            <div class="colored-boxed red">
                <h3><%= @content6.title %></h3>
                <span class="center-line"></span>
                <p>
                    <%= @content6.body %>
                </p>
                <% if user_signed_in? %>
                    <% if current_user.admin? %>
                        <%= link_to 'Edit', edit_content_path(@content6) %>
                    <% end %>
                <% end %>
            </div>
        </div><!--colored boxed col end-->
    </div>
</div><!--services container-->

<script type="text/javascript">
    document.getElementById("mainContainer").className = "";
</script>

app/views/home/productos.html.erb
<div class="divide70"></div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="center-heading">
                <h2><strong>Productos</strong></h2>
                <span class="center-line"></span>
            </div>
        </div>                   
    </div>
    <div class="row">
        <div class="col-sm-4 margin30">
            <div>
                <a href="#">
                    <div class="item-img-wrap">
                        <%= image_tag("transparente.png", class:'img-responsive') %>
                        <div class="item-img-overlay">
                            <span></span>
                        </div>
                    </div>                       
                </a>
                <div class="news-desc text-center">
                    <h4>Transparente</h4>
                </div>
            </div> 
        </div>
        <div class="col-sm-4 margin30">
            <div>
                <a href="#">
                    <div class="item-img-wrap">
                        <%= image_tag("imgDecovi.png", class:'img-responsive') %>
                        <div class="item-img-overlay">
                            <span></span>
                        </div>
                    </div>                       
                </a>
                <div class="news-desc text-center">
                    <h4>Glitter</h4>
                </div>
            </div> 
        </div>
        <div class="col-sm-4 margin30">
            <div>
                <a href="#">
                    <div class="item-img-wrap">
                        <%= image_tag("arqueologica.png", class:'img-responsive') %>
                        <div class="item-img-overlay">
                            <span></span>
                        </div>
                    </div>                       
                </a>
                <div class="news-desc text-center">
                    <h4>Argueológica</h4>
                </div>
            </div> 
        </div>
    </div>
</div>

app/views/home/reportes.html.erb
<div class="divide80"></div>
<div class="row">
	<div class="col-md-6">
		<table class="table table-hover">
		    <thead>
		        <tr>
		            <th>Producto</th>
		            <th>Ventas</th>
		        </tr>
		    </thead>
		    <tbody>
	    		<% @reporte.each do |r| %>
					<% @producto = Producto.find(r[0]) %>
					<tr>
						<td><%= @producto.nombre + ' ' + @producto.acabado %></td>
						<td><%= r[1] %></td>
					</tr>
				<% end %>
		    </tbody>
		</table>
	</div>
	<div class="col-sm-3">
        <div class="pricing-simple">
            <h4>Pedidos</h4>
            <h3><%= @cantPedidos %></h3>
            
        </div>
    </div>
    <div class="col-sm-3">
        <div class="pricing-simple">
            <h4>Usuarios</h4>
            <h4>Empresas: <%= @empresas %></h4>
            <h4>Individuo: <%= @individuos %></h4>
            
        </div>
    </div>
</div>

app/views/home/servicios.html.erb
<div class="divide80"></div>

<div class="container">
    <div class="center-heading">
        <h2>Servicios</h2>
        <span class="center-line"></span>
    </div>
    <div class="row">
        <div class="row special-feature">
                <div class="col-md-4 col-sm-6 margin20">
                    <div class="s-feature-box text-center">
                        <div class="mask-top">
                            <!-- Icon -->
                            <%= image_tag("shot-glass.png", class:'img-responsive center-block') %>
                            <!-- Title -->
                            <h4>Línea especial</h4>
                        </div>
                        <div class="mask-bottom">
                            <!-- Icon -->
                            <%= image_tag("shot-glass-small.png", class:'img-responsive center-block') %>
                            <!-- Title -->
                            <h4>Línea especial</h4>
                            <!-- Text -->
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec odio ipsum. Suspendisse cursus malesuada facilisis.</p>
                        </div>
                    </div>
                </div><!--services col-->
                <div class="col-md-4 col-sm-6 margin20">
                    <div class="s-feature-box text-center">
                        <div class="mask-top">
                            <!-- Icon -->
                            <%= image_tag("shot-glass.png", class:'img-responsive center-block') %>
                            <!-- Title -->
                            <h4>Evento</h4>
                        </div>
                        <div class="mask-bottom">
                            <!-- Icon -->
                            <%= image_tag("shot-glass-small.png", class:'img-responsive center-block') %>
                            <!-- Title -->
                            <h4>Evento</h4>
                            <!-- Text -->
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec odio ipsum. Suspendisse cursus malesuada facilisis.</p>
                        </div>
                    </div>
                </div><!--services col-->
                <div class="col-md-4 col-sm-6 margin20">
                    <div class="s-feature-box text-center">
                        <div class="mask-top">
                            <!-- Icon -->
                            <%= image_tag("shot-glass.png", class:'img-responsive center-block') %>
                            <!-- Title -->
                            <h4>Maquila</h4>
                        </div>
                        <div class="mask-bottom">
                            <!-- Icon -->
                            <%= image_tag("shot-glass-small.png", class:'img-responsive center-block') %>
                            <!-- Title -->
                            <h4>Maquila</h4>
                            <!-- Text -->
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec odio ipsum. Suspendisse cursus malesuada facilisis.</p>
                        </div>
                    </div>

                </div><!--services col-->
            </div>
    </div>
</div>